# Day 7 EOD: Forty Thousand Zip Codes

Date: 09/09/2026

In [1]:
# plt.figure(figsize=(w, h))                             # the canvas
# plt.xlabel(...) ; plt.ylabel(...) ; plt.title(...)     # always
# plt.tight_layout()                                     # last

# sns.scatterplot(data=df, x='col', y='col', hue='col')  # one measurement against another
# sns.histplot(data=df, x='col')                         # the shape of one column
# sns.barplot(x=series.values, y=series.index)           # a grouped Series, as bars

In [2]:
# pd.concat([a, b], ignore_index=True)                   # the stacking pattern
# pd.merge(left, right, left_on='a', right_on='b')       # the join pattern
# df.pivot_table(index=, columns=, values=)              # the pivot pattern
# df.groupby('key')['col'].agg(['count', 'mean'])        # split, apply, combine
# df.sort_values('col', ascending=False).head(n)         # the top-N pattern
# df['new'] = df['col'].apply(named_function)            # the derived-column pattern

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base = 'https://eds-217-essential-python.github.io/data/'

zones_2012 = pd.read_csv(base + 'hardiness_zones_2012.csv')
zones_2023 = pd.read_csv(base + 'hardiness_zones_2023.csv')
zipcodes = pd.read_csv(base + 'zip_code_database.csv')

Two lines of setup here use string operations we have not covered yet. Both do the same kind of job: they take a column of text and turn it into something you can join on or do arithmetic with. Copy them as given, and ask Cella or Kelly if you want the longer version!

Padding a zip code. All three files store zip codes as integers, so 01001 arrives as the number 1001 and the leading zero is gone. Two files that lost their zeros in the same way will still match each other, but the moment you print one or compare it to a real zip code you have a problem. .str.zfill(5) zero-fills a string out to five characters:

zones_2023['zipcode'] = zones_2023['zipcode'].astype(str).str.zfill(5)

Splitting a range. The trange column holds text like '-10 to -5'. To do arithmetic on the cold end of that range you need the first piece of it, as a number:

zones['trange_min'] = zones['trange'].str.split().str.get(0).astype(int)

.str.split() cuts the text at every space, giving ['-10', 'to', '-5']. .str.get(0) takes the first piece from each row. .astype(int) turns '-10' into -10.

On Thursday, in 4C, we said that chaining .str methods together was a Day 7 problem, and here is the chain. Three methods in a row, each one working on whatever the last one returned, which is the same pattern you have been reading all week in .sort_values(...).head(10). A chain is two patterns run one after the other.

In [4]:
zones_2023['zipcode'] = zones_2023['zipcode'].astype(str).str.zfill(5)
zones_2012['zipcode'] = zones_2012['zipcode'].astype(str).str.zfill(5)
zipcodes['zip'] = zipcodes['zip'].astype(str).str.zfill(5)

In [5]:
print(zones_2012.shape)
print(zones_2023.shape)
print(zipcodes.shape)
zipcodes.head()

(40534, 4)
(39921, 4)
(42522, 16)

,zip,type,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,latitude,longitude,world_region,country,decommissioned,estimated_population,notes
0,00501,UNIQUE,Holtsville,NaN,I R S Service Center,NY,Suffolk County,America/New_York,631,40.81,-73.04,NaN,US,0,384,NaN
1,00544,UNIQUE,Holtsville,NaN,Irs Service Center,NY,Suffolk County,America/New_York,631,40.81,-73.04,NaN,US,0,0,NaN
2,00601,STANDARD,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas,America/Puerto_Rico,"787,939",18.16,-66.72,NaN,US,0,0,NaN
3,00602,STANDARD,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,NaN,NaN,787,18.38,-67.18,NaN,US,0,0,NaN
4,00603,STANDARD,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla,America/Puerto_Rico,787,18.43,-67.15,NaN,US,0,0,NaN

In [7]:
zones_2012.head()

  zipcode zone      trange       zonetitle
0   01001   6a   -10 to -5   6a: -10 to -5
1   01002   5b  -15 to -10  5b: -15 to -10
2   01003   5b  -15 to -10  5b: -15 to -10
3   01004   5b  -15 to -10  5b: -15 to -10
4   01005   5b  -15 to -10  5b: -15 to -10

In [10]:
zones_2012['year'] = '2012'
zones_2023['year'] = '2023'
zones = pd.concat([zones_2012, zones_2023], ignore_index=True)  
zones

      zipcode zone      trange       zonetitle  year
0       01001   6a   -10 to -5   6a: -10 to -5  2012
1       01002   5b  -15 to -10  5b: -15 to -10  2012
2       01003   5b  -15 to -10  5b: -15 to -10  2012
3       01004   5b  -15 to -10  5b: -15 to -10  2012
4       01005   5b  -15 to -10  5b: -15 to -10  2012
...       ...  ...         ...             ...   ...
80450   99363   7b     5 to 10     7b: 5 to 10  2023
80451   99371   7a      0 to 5      7a: 0 to 5  2023
80452   99401   7a      0 to 5      7a: 0 to 5  2023
80453   99402   7a      0 to 5      7a: 0 to 5  2023
80454   99403   7b     5 to 10     7b: 5 to 10  2023

[80455 rows x 5 columns]

In [20]:
zones['trange_min'] = zones['trange'].str.split().str.get(0).astype(int)
zones.value_counts().sort_values().head(1)

zipcode  zone  trange     zonetitle      year  trange_min
01009    6a    -10 to -5  6a: -10 to -5  2012  -10           1
Name: count, dtype: int64

In [35]:
mean_year = zones.groupby('year')['trange_min'].mean()
mean_year
print(1.017259086696225+1.899886515024424)

2.917145601720649

In [ ]:
#df.rename(columns={"A": "a", "B": "c"})
zipcodes.rename(column={'zip': 'zipcode'})
merge_inner = pd.merge(zones, zipcodes, on='zipcode', how='inner')

TypeError: Series.rename() got an unexpected keyword argument 'column_names'