# Day 6: Session 6B - Long and Wide

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6b_reshaping_data.html)

Date: 09/08/2026

In [1]:
import pandas as pd

base = 'https://eds-217-essential-python.github.io/data/'

goleta = pd.read_csv(base + 'openaq_goleta_measurments.csv')
santa_barbara = pd.read_csv(base + 'openaq_santa_barbara_measurments.csv')
cnsi = pd.read_csv(base + 'openaq_CNSI_measurments.csv')

print(goleta.shape)
print(santa_barbara.shape)
print(cnsi.shape)

(1962, 15)
(2266, 15)
(714, 15)

In [2]:
## pd.merge() CANNOT stack tables. 
# pd.concat() CAN, and it takes a *list* of DataFrames:
aq = pd.concat([goleta, santa_barbara, cnsi])

aq.shape

(4942, 15)

In [28]:
## Label your pieces before you stack them so you don't loose track of the origin
goleta['site'] = 'Goleta'
santa_barbara['site'] = 'Santa Barbara'
cnsi['site'] = 'CNSI'

aq = pd.concat([goleta, santa_barbara, cnsi])
aq.shape

(4942, 16)

In [29]:
## Let's double check our numbers
print("SB: ", santa_barbara.shape)
print("Goleta: ", goleta.shape)
print("CSNI: ", cnsi.shape)
print(aq['site'].value_counts())

SB:  (2266, 16)
Goleta:  (1962, 16)
CSNI:  (714, 16)
site
Santa Barbara    2266
Goleta           1962
CNSI              714
Name: count, dtype: int64

In [ ]:
## pd.concat() by default preserves the index values of each dataframe...
# This means indices can repeat!
# Especially if indicies are row numbers
aq.loc[0]
# three zero locations

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider,site
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Goleta
0,27499,Santa Barbara,o3,0.022,ppm,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.427750,-119.690910,NaN,NaN,NaN,Unknown Governmental Organization,AirNow,Santa Barbara
0,2812592,CNSI Roof Top,pm25,4.400,µg/m³,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.415560,-119.840250,NaN,NaN,NaN,Clarity,Clarity,CNSI

### write the stacking pattern, pd.concat([a, b, c]), and say what ignore_index=True fixes

In [ ]:
# Use a new index to create a new index when using pd.concat()
# Set ignore_index=True
aq = pd.concat([goleta, santa_barbara, cnsi], ignore_index=True)
aq.loc[0]
# only one zero location

location_id                                   1186
location_name                               Goleta
parameter                                       o3
value                                        0.025
unit                                           ppm
datetimeUtc              2024-07-12T01:00:00+00:00
datetimeLocal            2024-07-11T18:00:00-07:00
timezone                       America/Los_Angeles
latitude                                 34.445301
longitude                              -119.827797
country_iso                                    NaN
isMobile                                       NaN
isMonitor                                      NaN
owner_name       Unknown Governmental Organization
provider                                    AirNow
site                                        Goleta
Name: 0, dtype: object

#### ignore_index=True fixes the index order- don't forget!

In [39]:
## Practice:
aq_reordered = pd.concat([cnsi, goleta, santa_barbara])
aq_reordered.shape

(4942, 16)

In [40]:
aq_reordered.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider,site
0,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
1,2812592,CNSI Roof Top,pm25,4.4,µg/m³,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
2,2812592,CNSI Roof Top,pm25,4.6,µg/m³,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
3,2812592,CNSI Roof Top,pm25,4.2,µg/m³,2024-07-11T05:00:00+00:00,2024-07-10T22:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI
4,2812592,CNSI Roof Top,pm25,4.5,µg/m³,2024-07-11T06:00:00+00:00,2024-07-10T23:00:00-07:00,America/Los_Angeles,34.41556,-119.84025,NaN,NaN,NaN,Clarity,Clarity,CNSI

In [41]:
aq_reordered.value_counts('site')

site
Santa Barbara    2266
Goleta           1962
CNSI              714
Name: count, dtype: int64

### describe the difference between a long table and a wide one, and say what each is good at

A **long** table can be appended to forever without ever changing its columns, BUT a long table is awkward to compare across. To make this easier a **wide** table allows you to make a comparison by reading two numbers that are already sitting next to each other.

In [42]:
aq[['site', 'parameter', 'value', 'unit', 'datetimeLocal']].head()

     site parameter  value unit              datetimeLocal
0  Goleta        o3  0.025  ppm  2024-07-11T18:00:00-07:00
1  Goleta        o3  0.028  ppm  2024-07-11T19:00:00-07:00
2  Goleta        o3  0.029  ppm  2024-07-11T20:00:00-07:00
3  Goleta        o3  0.027  ppm  2024-07-11T21:00:00-07:00
4  Goleta        o3  0.026  ppm  2024-07-11T22:00:00-07:00

### write the pivot pattern, pivot_table(index=, columns=, values=), and read its result

In [ ]:
## pivot_table() rotates a DataFrame from long to wide

# df.pivot_table(index='rows', columns='columns', values='numbers')
# #              ↑             ↑                  ↑
# #              what labels   what labels        what goes
# #              the rows      the columns        in the cells

In [ ]:
aq.pivot_table(
    index='site',
    columns='parameter',
    values='value'
)
## **by default, pivot_table() takes the average of the column values**

parameter            o3       pm10      pm25
site
CNSI                NaN        NaN  6.083473
Goleta         0.022470  14.972921  6.480926
Santa Barbara  0.019822  17.563969  6.172324

In [58]:
## use agg.func= to assign a different statistical method
aq_count = aq.pivot_table(
    index='site', columns='parameter', values='value', aggfunc='count')
aq_count

parameter         o3   pm10   pm25
site
CNSI             NaN    NaN  714.0
Goleta         711.0  517.0  734.0
Santa Barbara  734.0  766.0  766.0

In [64]:
means = aq.pivot_table(index='site', columns='parameter', values='value')
means
# site becomes index

parameter            o3       pm10      pm25
site
CNSI                NaN        NaN  6.083473
Goleta         0.022470  14.972921  6.480926
Santa Barbara  0.019822  17.563969  6.172324

In [63]:
# use .reset.index() to reset the site to a column
flat = means.reset_index()
flat

parameter           site        o3       pm10      pm25
0                   CNSI       NaN        NaN  6.083473
1                 Goleta  0.022470  14.972921  6.480926
2          Santa Barbara  0.019822  17.563969  6.172324

In [69]:
## Practice:
swap_aq = aq.pivot_table(
    index='parameter',
    columns='site',
    values='value',
    aggfunc='mean'
)
swap_aq

site           CNSI     Goleta  Santa Barbara
parameter
o3              NaN   0.022470       0.019822
pm10            NaN  14.972921      17.563969
pm25       6.083473   6.480926       6.172324


turn a .value_counts() result back into a table you can merge with, using .reset_index()

In [82]:
# pd.merge() needs two DataFrames with columns to join on 
# and a Series has an index where the column would be. 
# So we promote it into a DataFrame:

counts = aq['site'].value_counts().reset_index()
counts

            site  count
0  Santa Barbara   2266
1         Goleta   1962
2           CNSI    714

In [83]:
counts = counts.rename(columns={'count': 'n_readings'})
counts

            site  n_readings
0  Santa Barbara        2266
1         Goleta        1962
2           CNSI         714

In [84]:
# new_df = df['column'].value_counts().reset_index()
# counts = counts.rename(columns={'count': 'a_better_name'})

In [85]:
summary = pd.merge(flat, counts, on='site')
summary

            site        o3       pm10      pm25  n_readings
0           CNSI       NaN        NaN  6.083473         714
1         Goleta  0.022470  14.972921  6.480926        1962
2  Santa Barbara  0.019822  17.563969  6.172324        2266


say which shape you want before you start writing code

### Key points
pd.concat([a, b, c]) stacks tables with the same columns, top to bottom. It matches nothing and drops nothing.

Label the pieces before you stack them. Once the rows are combined, there is no way to recover which file a row came from.

Use ignore_index=True so the stacked table gets one clean set of row numbers.

A long table has one measurement per row and its labels in columns. It is easy to append to and hard to compare across.

A wide table has one row per thing and one column per measurement. It is easy to compare and awkward to extend.

The pivot pattern is df.pivot_table(index=, columns=, values=). It goes long to wide.

pivot_table averages by default. Pass aggfunc='count' and look at that version first.

The result is indexed by the index= column. .reset_index() turns it back into a plain table.

.value_counts().reset_index() promotes a count Series into a two-column table you can merge with. Rename the count column while you are there.